### ISSUE TITLE
Alpha Checklist

### ISSUE THREAD

**Issue by riordanp** [riordanp/steamchat#1]
- [x] Logging in and dealing with steamguard/sentry hash
- [x] Correctly display friends and avatars
- [x] Chat functionality
- [ ] Settings Pane
    - [ ] Change profile information (display name, avatar)
    - [ ] Notification Settings
    - [ ] Design Settings
- [ ] Send messages on Enter key and require Shift + Enter for a new line
- [ ] Unread message notifications
- [ ] Change online status dropdown
- [ ] Friend groups (Favourites, Offline etc)
- [ ] Chat logging (What format?)
- [ ] Polish chat pane
- [ ] Group chats
